---
title: "Compare editing frequencies across tissues"
author: "Kent Riemondy RBI"
date: "6/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r ,message=FALSE, warning=FALSE}
source("globals.R")
```

## Editing patterns across brain regions and other tissues


```{r}
pdata <- read_tsv(file.path(docs_dir, "BrainRegionRNAseqLibMetadata.txt"))
pdata <- gather(pdata, region, sample, Forebrain, Hypothalamus, Medulla)
  
pdata <- mutate(pdata,
                region = ifelse(region == "Forebrain",
                                "Cerebrum",
                                region))
pdata <- mutate(pdata, 
                  abbrev_sample = str_split(sample, "_", simplify = T)[, 1])
```

```{r}
gatk_annot <- read_tsv("edits/geo/gatk_sites_annotation.txt.gz")
gatk_prop <- read_tsv("edits/variant_allele_counts_by_strand/A_G_alleles/A_G_filtered_sites_proportions.txt.gz")
hyper_prop <- read_tsv("hyperedits/diffedits/A_G_filtered_sites_proportions.txt.gz")
hyper_annot <-  read_tsv("edits/geo/hyperedited_sites_annotation.txt.gz")

sig_sites <- readxl::read_excel("Figures/Supplemental-Table-3.xlsx", 2)
sig_gatk_sites <- filter(sig_sites, edit_type == "gatk") %>% pull(site) %>% unique()
sig_hyper_sites <- filter(sig_sites, edit_type == "hyperedited") %>% pull(site) %>% unique()
both_sites <- filter(sig_sites, edit_type == "both") %>% pull(site) %>% unique()

gatk_prop_sig <- filter(gatk_prop, edit_site %in% sig_gatk_sites | edit_site %in% both_sites)
hyper_prop_sig <- filter(hyper_prop, edit_site %in% sig_hyper_sites)
hyper_prop_sig <- hyper_prop_sig[, colnames(gatk_prop_sig)]
brain_site_proportions <- bind_rows(gatk_prop_sig, hyper_prop_sig)
```


```{r io_util_functions}
bp_comp <- function(nt){
  #return complementary basepair
  comp <- c("A", "G", "T", "C")
  names(comp) <- c("T", "C", "A", "G")
  comp[nt] %>% unname()
}

group_dat <- function(.dir, .pattern, ...){
  # read in and aggregate data into matrix-like format
  files <- dir(.dir, 
             full.names = T,
             pattern = .pattern, ...)
  dat <- suppressMessages(map(files,  ~readr::read_tsv(.x,  col_names = T, progress = F)))
  dat <- Reduce(function(x, y) inner_join(x, y, by = c("#chrom", "pos", "ref", "base")), dat)
  colnames(dat) <- c("#chrom", "pos", "ref", "base", basename(files))
  dat
}  

write_gztsv <- function(df, name, ...){
  # write output as gzipped, supply name without .gz
  if(str_detect(name, ".gz$")){
    uncompressed_name <- str_replace(name, ".gz$", "")
  } else {
    uncompressed_name <- name
  }
  write_tsv(df, uncompressed_name, ...)
  system(paste0("gzip -f ", uncompressed_name))
}
```

```{r}
# get raw counts

regions = c("medulla", "hypothalamus", "brainrest")
dat <- map(regions, ~group_dat(file.path(data_dir, 
              "vcf/variant_allele_counts_by_strand/A_G_alleles/counts",
              .x), 
              ".gz"))
names(dat) <- regions

hyper_dat <- map(regions, ~group_dat(file.path(data_dir, 
              "hyperedits/site_counts/A_G_counts",
              .x), 
              ".gz"))
names(hyper_dat) <- regions

combined_dat <- map2(dat, 
            hyper_dat,
            ~bind_rows(.x,
                 .y) %>% 
              unique(.))

combined_dat <- map(combined_dat, 
                    ~mutate(.x, edit_site = paste(`#chrom`, pos, ref, sep = "::")))
```

```{r lib_sizes, message=F}

.dir <- file.path(data_dir, "star")
star_report_files <- dir(.dir,
                         pattern = "*_2pass_Log.final.out",
                         recursive = T, full.names = T)

star_reports <- suppressWarnings(map(star_report_files,
                    ~read_tsv(.x, col_names = F)))

star_report_names <- basename(star_report_files) %>%
  str_replace(., "_2pass_Log.final.out", "")

names(star_reports) <- star_report_names
lib_sizes <- map(star_reports,
                 ~dplyr::filter(.x,
                                X1 == "Uniquely mapped reads number |") %>%
                   dplyr::select(X2))

lib_sizes <- bind_rows(lib_sizes, .id = "library") %>%
  dplyr::rename(lib_size = X2) %>%
  dplyr::mutate(lib_size = as.numeric(lib_size))

extract_lib_sizes <- function(.names, lib_sizes_df) {
  #get original mapped to exons count for selected libraries
  suffix_names <- str_replace(.names, "_counts.txt.gz$", "")
  suffix_names_df <- data_frame(original_name = suffix_names,
                                fq_name = .names)
  sizes <- left_join(suffix_names_df, lib_sizes_df, 
                     by = c("original_name" = "library"))
  sizes <- dplyr::select(sizes, -original_name)
  sizes
}

lib_names <- map(combined_dat, ~colnames(.x) %>%
                   str_subset(., ".gz$")) %>%
  unlist() %>% unname()

lib_sizes_df <- extract_lib_sizes(lib_names, lib_sizes)


mod_combined_dat <- map(combined_dat,
                      ~dplyr::select(.x, edit_site, base,
                              -`#chrom`, -pos, -ref,
                              ends_with(".gz")))

mod_combined_dat <- map(mod_combined_dat,
                        ~.x %>% 
                          gather(library, counts, -edit_site, -base) %>% 
                          left_join(., lib_sizes_df, by = c("library" = "fq_name")))

mod_combined_dat <- map(mod_combined_dat,
                        ~.x %>% 
                          mutate(norm_counts = 1e6 * (counts / lib_size)))

mod_combined_dat <- map(mod_combined_dat, 
                        ~.x %>% 
                          dplyr::select(edit_site, library, base, 
                                        counts = norm_counts) %>% 
                          spread(library, counts))

```


```{r}
sig_combined_dat <- map(mod_combined_dat,
                       ~filter(.x, edit_site %in% sig_sites$site))


sig_combined_dat <- map(sig_combined_dat,
                      ~dplyr::select(.x, edit_site, 
                               -base, ends_with(".gz")))

row_coverage <- map(sig_combined_dat, 
                    ~rowMeans(.x[, -1]))
sig_combined_dat$medulla$total_coverage <- row_coverage[[1]]
sig_combined_dat$hypothalamus$total_coverage <- row_coverage[[2]]
sig_combined_dat$brainrest$total_coverage <- row_coverage[[3]]
  
sig_combined_dat <- map(sig_combined_dat, 
                        ~dplyr::select(.x, edit_site, total_coverage))
sig_combined_dat <- map(sig_combined_dat, 
                        ~dplyr::group_by(.x, 
                                         edit_site) %>% 
                          summarize(raw_count = sum(total_coverage)))
sig_combined_dat <- bind_rows(sig_combined_dat, 
                              .id = "region")

sig_combined_dat <- left_join(sig_combined_dat, 
                              n_sig_regions, by = c("edit_site" = "site"),
                              suffix = c("_site",
                                         "_site_sig"))

sig_combined_plot_dat <- mutate(sig_combined_dat, 
                           n_sig = as.factor(n),
                           log2_count = log2(raw_count),
                           region_site = ifelse(region_site == "medulla",
                                           "Medulla",
                                           ifelse(region_site == "hypothalamus",
                                                  "Hypothalamus",
                                                  "Cerebrum")),
                           region_site = factor(region_site,
                                                   levels = c(
                                                     "Medulla",
                                                     "Cerebrum",
                                                     "Hypothalamus"
                                                   )))

p <- ggplot(sig_combined_plot_dat, 
            aes(n_sig, log2_count)) +
  geom_boxplot(aes(fill = region_site), coef = Inf) +
  scale_fill_manual(values = region_cols, 
                    name = "") +
  labs(x = "# of Brain Regions Each\nSite is Called Signficiant",
       y = expression(paste("Mean Normalized Coverage (log"[2],")"))) +
  theme(legend.position = "top")
p

save_plot("edits/read_coverage_vs_n_regions.pdf", 
          p)

file.copy("edits/read_coverage_vs_n_regions.pdf",
          sfigs_dir[10], overwrite = T)


sig_combined_per_region<- mutate(sig_combined_dat, 
                           region_site = ifelse(region_site == "medulla",
                                           "Medulla",
                                           ifelse(region_site == "hypothalamus",
                                                  "Hypothalamus",
                                                  "Forebrain")))


sig_combined_per_region <- sig_combined_per_region %>% 
  filter(str_detect(region_site_sig, region_site))

sig_combined_plot_dat <- mutate(sig_combined_per_region, 
                           n_sig = as.factor(n),
                           log2_count = log2(raw_count),
                           region_site =ifelse(region_site == "Forebrain",
                                               "Cerebrum",
                                               region_site))

p <- ggplot(sig_combined_plot_dat, 
            aes(n_sig, log2_count)) +
  geom_boxplot(aes(fill = region_site), coef = Inf) +
  facet_wrap(~region_site) +
  scale_fill_manual(values = region_cols) +
  labs(x = "# of Brain Regions Each\nSite is Called Signficiant",
       y = expression(paste("Read Coverage (log"[2],")"))) +
  theme(legend.position = "none")
p

save_plot("edits/read_coverage_vs_n_regions_found_in_each_region.pdf", 
          p)

```


## compare brain regions 

```{r}
gatk_sites <- read_tsv("edits/A_G_filtered_fdr0.01_sites_annotation_kmeans.txt.gz")
gatk_sites <- dplyr::filter(gatk_sites, 
                            kmeans_cluster == 1) %>% 
  dplyr::select(site, Region) %>% 
  split(., .$Region) %>% 
  map(., pull, site)

hyperedited_sites <- read_tsv("hyperedits/diffedits/A_G_filtered_sites_annotation_kmeans.txt.gz")
hyperedited_sites <- hyperedited_sites %>% 
  dplyr::filter(kmeans_cluster != 3, 
                FDR < 0.01) %>% 
  dplyr::select(site, Region) %>% 
  split(., .$Region) %>% 
  map(., pull, site)

names(gatk_sites) <- map_chr(names(gatk_sites), 
                             ~ifelse(.x == "Forebrain", 
                            "Cerebrum",
                            .x))

names(hyperedited_sites) <- map_chr(names(hyperedited_sites), 
                                    ~ifelse(.x == "Forebrain", 
                            "Cerebrum",
                            .x))

set.seed(20171020)
fit <- eulerr::euler(gatk_sites)

pdf("edits/gatk_sites_per_region.pdf")
plot(fit, 
     fill = region_cols[c(3,2,1)],
     fill_opacity = 0.55,
     counts = list(cex = 2, col = "black"), 
     lwd = 3,
     cex = 2,   
     main = NULL,
     col = "black")
dev.off()
file.copy("edits/gatk_sites_per_region.pdf",
          sfigs_dir[10], overwrite = T)

set.seed(20171020)
fit <- eulerr::euler(hyperedited_sites)

pdf("edits/hyperedited_sites_sites_per_region.pdf")
plot(fit, 
     fill = region_cols[c(3,2,1)],
     fill_opacity = 0.55,
     counts = list(cex = 2, col = "black"), 
     lwd = 3,
     cex = 2,   
     main = NULL,
     col = "black")
dev.off()

file.copy("edits/hyperedited_sites_sites_per_region.pdf",
          sfigs_dir[10], overwrite = T)
```


## Finding editing sites that are different between tissues

In this case, an editing site will be called as having a tissue specific difference if it is found significant in 1 or 2 regions, and has a similar coverage level in the non-significant tissue. 

```{r}

get_non_intersecting <- function(list_of_vectors) {
  res <- list()
  for(i in 1:length(list_of_vectors)){
    others <- setdiff(1:length(list_of_vectors), i)
    not_shared <- setdiff(list_of_vectors[[i]],
            unname(unlist(list_of_vectors[others])))
    res[[i]] <- not_shared
  }
  res
}
both_sites <- map2(gatk_sites, hyperedited_sites, c)
tissue_edits <- get_non_intersecting(gatk_sites)
names(tissue_edits) <- names(both_sites)

tissue_edits <- map(tissue_edits, 
                    ~data_frame(edit_site = .x)) %>% 
  bind_rows(., .id = "region")

tissue_edits_plt <- left_join(tissue_edits,
                          sig_combined_dat,
                          by = "edit_site") %>% 
 mutate(region_site = ifelse(region_site == "medulla",
                                           "Medulla",
                                           ifelse(region_site ==
                                                    "hypothalamus",
                                                  "Hypothalamus",
                                                  "Cerebrum")))


tissue_edits_plt <- mutate(tissue_edits_plt, 
                           log2_count = log2(raw_count))

ggplot(tissue_edits_plt, 
       aes(region_site, log2_count)) +
  geom_boxplot(aes(fill = region_site), coef = Inf) +
  facet_wrap(~region) +
  scale_fill_manual(values = region_cols, 
                    name = "") +
  labs(x = "# of Brain Regions Each\nSite is Called Signficiant",
       y = expression(paste("Mean Normalized Coverage (log"[2],")"))) +
  theme(legend.position = "top",
        axis.text.x = element_blank())


sig_combined_per_region <- mutate(sig_combined_per_region,
                                  region = ifelse(region_site == "Forebrain",
                                                  "Cerebrum",
                                                  region_site))
tissue_edits_coverage <- left_join(tissue_edits,
                          sig_combined_per_region,
                          by = c("edit_site",
                                 "region"))

tissue_edits_coverage <- mutate(tissue_edits_coverage, 
                                sig_site_count = raw_count) %>% 
  dplyr::select(-raw_count, -region_site, -n, -region_site_sig)

sig_combined_plot_dat <- mutate(sig_combined_dat, 
                           region_site = ifelse(region_site == "medulla",
                                           "Medulla",
                                           ifelse(region_site == "hypothalamus",
                                                  "Hypothalamus",
                                                  "Cerebrum")))

tissue_edits_coverage <- left_join(tissue_edits_coverage,
                                   sig_combined_plot_dat,
                                   by = c("edit_site"))

hyper_annot_unique <- hyper_annot[!hyper_annot$site %in% gatk_annot$site, 
                                  ]

annot <- bind_rows(gatk_annot, hyper_annot_unique)
annot <- annot %>% mutate(Region = ifelse(Region == "Forebrain",
                                                    "Cerebrum",
                                                    Region))

fdr <- annot %>% dplyr::select(region = Region, site, FDR)

tissue_edits_coverage <- left_join(tissue_edits_coverage, 
                                   fdr, 
                                   by = c("edit_site" = "site", "region_site" = "region"))

non_edited_high_coverage <- tissue_edits_coverage %>% 
   filter(raw_count >= sig_site_count,
          region != region_site,
          FDR > 0.5) 
sig_edits <- tissue_edits_coverage %>% 
  filter(FDR < 0.01, 
         region == region_site)

tissue_variable_edits <- bind_rows(non_edited_high_coverage, sig_edits) %>% 
  group_by(edit_site) %>% 
  mutate(n_sites_left = n()) %>% 
  filter(n_sites_left > 1) 
```



```{r}
long_prop_dat <- read_tsv(file.path("edits", "variant_allele_counts_by_strand",
                                    "A_G_alleles", "A_G_filtered_sites_proportions_tidy.txt.gz"))

annot_dat <- read_tsv("edits/variant_allele_counts_by_strand/A_G_alleles/A_G_filtered_sites_annotation.txt.gz")

plot_sites <- function(prop_dat, 
                       toptag_dat, 
                       stat_region = "Medulla", 
                       region_to_plot = "all", 
                       sites_to_plot = c("GRIA2"),
                       name_col = "site",
                       save = T,
                       title = NULL, ...) {
  
    col_palette <- c(
    SA = rgb(255, 0, 0, maxColorValue=255),
    IBA = rgb(67, 205, 128, maxColorValue=255),
    Ent = rgb(155, 48, 255, maxColorValue=255),
    LT = rgb(25, 25, 112, maxColorValue=255),
    Ar = rgb(0, 0, 255, maxColorValue=255),
    SpD = rgb(255, 165, 0, maxColorValue=255) 
  )

  state_order = c(
    "SA", "IBA", "Ent", "LT", "Ar", "SpD"
  )

  tt_dat_med <- filter_(toptag_dat, 
                        lazyeval::interp(quote(Region == x), x = stat_region)) %>% 
    filter(site %in% sites_to_plot) %>%  
    dplyr::select(site) %>% 
    unlist()
  
  tt_dat_med <- filter(toptag_dat, site %in% tt_dat_med)
  
  if (!region_to_plot == "all"){
    prop_dat <- prop_dat %>% filter_(lazyeval::interp(quote(Region == x), 
                                                      x = region_to_plot))
  }
  
  plot_dat <- inner_join(prop_dat, 
                         tt_dat_med, 
                         by = c("site", "Region"))
  
  gene_labels <- plot_dat[[name_col]] %>% unlist()
  
  names(gene_labels) <- plot_dat %>% 
    dplyr::select(site) %>% 
    unlist()
  
  plot_dat <- mutate(plot_dat, 
                State = factor(State, 
                        levels = state_order),
                Region = ifelse(Region == "Forebrain",
                                "Cerebrum",
                                Region),
                proportion = 100 * proportion)
    
  annot <- group_by(plot_dat, site, Region) %>% 
    summarize(FDR = paste0("FDR = ", signif(min(FDR), 3)))

  p <- ggplot(plot_dat, aes(State, proportion)) +
    #geom_boxplot(aes(fill = State), outlier.shape = NA) +
    geom_jitter(width = 0.25,
              aes(color = State)) +
    stat_summary(fun.y = "mean", 
               fun.ymin = "mean", 
               fun.ymax= "mean",
               size = 0.3,
               width = 0.75,
               geom = "crossbar") +
    facet_grid(Region ~ site, labeller = labeller(site = gene_labels)) + 
    scale_color_manual(values = col_palette, guide = guide_legend(nrow = 1)) +
    geom_text(data = annot, aes(x = 3.5, y = 95, label = FDR ), size = 3) + 
    ylab("Editing Frequency (%)") + 
    guides(fill=guide_legend(nrow=2,byrow=TRUE)) +
    theme(legend.position = "top",
          axis.text.x = element_blank(),
          strip.text = element_text(size = 9)
          )
  if(save){
    if(is.null(title)) {
      save_plot(paste0("edits/", gene_labels[1], "_boxplot.pdf"), p, ...)
    } else {
      save_plot(title, p, ...) 
    }
  }
  p
}

```


```{r}
tissue_variable_edits %>% 
  filter(sig_site_count > 0.5) %>% 
  arrange(FDR) %>% 
  ungroup() %>% 
  dplyr::slice(1:5) %>% 
  dplyr::pull(edit_site) -> sites_to_plot

mutate(annot_dat, annotation_id = ifelse(!is.na(GENE_NAME),
                                         GENE_NAME,
                                         ifelse(!is.na(DENOVO_GENE_ID),
                                                DENOVO_GENE_ID,
                                                str_c(chrom, ":", start))),
       annotation_id = str_split(annotation_id, ",", simplify = T)[, 1]) -> annot_dat

p <- plot_sites(long_prop_dat,
           annot_dat, 
          sites_to_plot = sites_to_plot, name_col = "annotation_id", save = F)
p <- p + theme(strip.text = element_text(size = 9))
save_plot("edits/tissue_specific_edits.pdf", p, 
          base_height = 6,
          base_width = 8)
file.copy("edits/tissue_specific_edits.pdf",
          sfigs_dir[10], overwrite = T)
```


```{r}
raw_dat <- read_tsv(file.path("edits", "variant_allele_counts_by_strand",
                              "A_G_alleles/A_G_all_sites_raw_counts.txt.gz"))

raw_dat <- semi_join(raw_dat, 
                     data_frame(edit_site = non_edited_high_coverage$edit_site),
                     by = "edit_site")

gatk_count_data <- raw_dat %>% 
  dplyr::select(-c(`#chrom`:ref)) %>% 
  gather(key = "library", value = "counts", -edit_site, -base)


gatk_count_data <- gatk_count_data %>% 
  mutate(abbrev_sample = str_match(library,
                                   "[MHB][0-9]+")) %>% 
  left_join(pdata, by = c("abbrev_sample"))

## exclude brain regions that were significant for each site
region_to_exclude <- non_edited_high_coverage %>%
  dplyr::select(edit_site, region) %>% unique()


gatk_count_data <- left_join(gatk_count_data,
                             region_to_exclude, 
                             by = "edit_site",
                             suffix= c("_library", "_sigsite"))
gatk_count_data <- filter(gatk_count_data,
                          region_library != region_sigsite)
# set gatk_count_data
gatk_count_data <- mutate(gatk_count_data,
                     State = factor(State, levels = state_order))

gatk_count_data <- gatk_count_data %>% 
  spread(base, counts)

index_data <- group_by(gatk_count_data, State, 
                       region_library) %>% 
  summarize(editing_index = sum(G) / (sum(A) + sum(G))) %>% 
  ungroup()


p <- ggplot(index_data, aes(State, editing_index)) +
  geom_smooth(method = "loess", color = "black", aes(group = region_library)) +
  geom_point(aes(color = region_library), size = 3, show.legend = T) +
  scale_colour_manual(values = region_cols) +
  ylab("Editing Index") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12, 
                                   colour = state_cols),
        legend.position = "top",
        legend.title = element_blank(),
        legend.text = element_text(size = 12))

save_plot("edits/tissue_specific_editing_index.pdf", p,
          base_height = 5, base_width = 4)
file.copy("edits/tissue_specific_editing_index.pdf",
          sfigs_dir[10], overwrite = T)
```